server:
  port: 9520

spring:
  application:
    name: jdbcoauth
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.1.157:3306/zuu_auth?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://127.0.0.1:8761/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      filter-order: 3


